# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.require_version ">= 1.6.2"

Vagrant.configure("2") do |config|
    config.vm.define "vagrant-windows-2008-r2"
    config.vm.box = "win2008R2"
    config.vm.communicator = "winrm"
    config.vm.hostname = "nk03"
    #config.vm.network "public_network", ip: "192.168.0.20"
    config.vm.network "public_network", :mac => "080027663038"
    # Admin user name and password
    config.winrm.username = "vagrant"
    config.winrm.password = "vagrant"

    config.vm.guest = :windows
    config.windows.halt_timeout = 15

    config.vm.network :forwarded_port, guest: 5986, host: 5986, id: "winrm-https", auto_correct: true
    config.vm.network :forwarded_port, guest: 3389, host: 3389, id: "rdp", auto_correct: true
    config.vm.network :forwarded_port, guest: 22, host: 2222, id: "ssh", auto_correct: true
    
    config.proxy.http     = "<>"
    config.proxy.https    = "<>"
    config.proxy.no_proxy = "localhost,127.0.0.1"
    
    config.vm.provider :virtualbox do |v, override|
        #v.gui = true
        v.customize ["modifyvm", :id, "--memory", 2048]
        v.customize ["modifyvm", :id, "--cpus", 2]
        v.customize ["setextradata", "global", "GUI/SuppressMessages", "all" ]
    end

end
